[package]
name = "tui-collab"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = { version = "0.29.0", features = ["all-widgets"] }
color-eyre = "0.6"
figlet-rs = "0.1.5"
uuid = { version = "1.18.1", features = ["v4"] }
chrono = "0.4.41"
tui-textarea = "0.7.0"